///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class AppAssets {
  AppAssets._();
  static const String egyptFlag = 'assets/images/egypt_flag.png';
  static const String frenchFlag = 'assets/images/french_flag.png';
  static const String americanFlag = 'assets/images/america_flag.png';
  static const String activeTranslateSvg = 'assets/images/active_translate.svg';
  static const String inActiveTranslateSvg = 'assets/images/inactive_translate.svg';
  static const String activeDictionarySvg = 'assets/images/active_dictionary.svg';
  static const String inActiveDictionarySvg = 'assets/images/inactive_dictionary.svg';
  static const String activePersonSvg = 'assets/images/active_person.svg';
  static const String inActivePersonSvg = 'assets/images/inactive_person.svg';
  static const String activeGearSvg = 'assets/images/active_gear.svg';
  static const String inActiveGearSvg = 'assets/images/inactive_gear.svg';

}
